# Generated by Django 5.2.10 on 2026-02-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Demand Report',
                'verbose_name_plural': 'Demand Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Recommendation Report',
                'verbose_name_plural': 'Recommendation Reports',
                'managed': False,
            },
        ),
    ]
