# Generated by Django 5.2.10 on 2026-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crops',
            field=models.ManyToManyField(blank=True, to='market.crop'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_markets',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
