# Generated by Django 5.2.10 on 2026-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_crop_image_user_profile_image_cropdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested')], default='planted', max_length=20),
        ),
        migrations.AddField(
            model_name='crop',
            name='type',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('legumes', 'Legumes')], default='vegetables', max_length=20),
        ),
    ]
